/*
 * ProCAKE Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.4
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ProCakeRestApi) {
      root.ProCakeRestApi = {};
    }
    root.ProCakeRestApi.ConversionControllerApi = factory(root.ProCakeRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * ConversionController service.
   * @module api/ConversionControllerApi
   * @version 1.0.4
   */

  /**
   * Constructs a new ConversionControllerApi. 
   * @alias module:api/ConversionControllerApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the convert operation.
     * @callback module:api/ConversionControllerApi~convertCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Start conversion with specified converter
     * 
     * @param {String} converterID 
     * @param {Object} opts Optional parameters
     * @param {String} opts.body Name (ID) of the converted NEST Workflow - Required for BPMNtoNEST Converter
     * @param {module:api/ConversionControllerApi~convertCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.convert = function(converterID, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'converterID' is set
      if (converterID === undefined || converterID === null) {
        throw new Error("Missing the required parameter 'converterID' when calling convert");
      }


      var pathParams = {
        'converterID': converterID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/xml'];
      var accepts = ['application/xml'];
      var returnType = null;

      return this.apiClient.callApi(
        '/conversion/{converterID}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getConverters operation.
     * @callback module:api/ConversionControllerApi~getConvertersCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch available converters
     * 
     * @param {module:api/ConversionControllerApi~getConvertersCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getConverters = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = [];
      var accepts = ['application/xml', 'application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/conversion/info', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
