/*
 * ProCAKE Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.4
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProCakeRestApi);
  }
}(this, function(expect, ProCakeRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProCakeRestApi.ConversionControllerApi();
  });

  describe('(package)', function() {
    describe('ConversionControllerApi', function() {
      describe('convert', function() {
        it('should call convert successfully', function(done) {
          // TODO: uncomment, update parameter values for convert call
          /*
          var converterID = "converterID_example";
          var opts = {};
          opts.body = "body_example";

          instance.convert(converterID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getConverters', function() {
        it('should call getConverters successfully', function(done) {
          // TODO: uncomment getConverters call
          /*

          instance.getConverters(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
